// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6DIgaL5BuplIQEEqgDfpjC1PqbDvFRI8',
    appId: '1:857968841245:web:359db2f691fb4e55eeacf4',
    messagingSenderId: '857968841245',
    projectId: 'trucker-2ba77',
    authDomain: 'trucker-2ba77.firebaseapp.com',
    storageBucket: 'trucker-2ba77.appspot.com',
    measurementId: 'G-8RBK822V6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTOTj5QQAu0_meN3qvHEfbXe2B0KBNVnE',
    appId: '1:857968841245:android:d5fc3ac244a75839eeacf4',
    messagingSenderId: '857968841245',
    projectId: 'trucker-2ba77',
    storageBucket: 'trucker-2ba77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtNx3ds9pD2Oj9ZWO4PoYGHtURsw7vY-4',
    appId: '1:857968841245:ios:cd864e7dcc9d24f5eeacf4',
    messagingSenderId: '857968841245',
    projectId: 'trucker-2ba77',
    storageBucket: 'trucker-2ba77.appspot.com',
    iosBundleId: 'com.example.truckerfinal',
  );
}
